sdzblog_accueil:
    path:    /{page}
    defaults: { _controller: SdzBlogBundle:Blog:index, page: 1}
    requirements:
        page: \d*
sdzblog_voir:
    path:    /article/{id}
    defaults: { _controller: SdzBlogBundle:Blog:voir}
sdzblog_ajouter:
    path:    /ajouter
    defaults: { _controller: SdzBlogBundle:Blog:ajouter}
sdzblog_ajouter:
    path:    /modifier/{id}
    defaults: { _controller: SdzBlogBundle:Blog:modifier}
    requirements:
        id: \d+
sdzblog_ajouter:
    path:    /suprimer/{id}
    defaults: { _controller: SdzBlogBundle:Blog:suprimer}
    requirements:
        id: \d+
sdzblog_voir_slug:
    path:     /{annee}/{slug}.{format}
    defaults: { _controller: SdzBlogBundle:Blog:voirSlug }
    requirements:
        annee:    \d{4}
        format:    html|xml